exports.SELECTORS_XP = {
  CHANNEL_NAME_XP: '//*[@id="root"]/div/div[2]/div[1]/main/div[2]/div[3]/div/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/div[2]/div[1]/div[1]/a/h1',
  CHANNEL_SUBSCRIBER_COUNT_XP: '//*[@id="subscriber-count"]',
  JOINED_DATE_XP: '//*[@id="right-column"]/yt-formatted-string[2]/span[2]',
  TOTAL_VIEW_COUNT_XP: '//*[@id="right-column"]/yt-formatted-string[3]',
  CHANNEL_DESCRIPTION_XP: '//*[@id="primary"]//*[@id="description-container"]//*[@id="description"]',
  CHANNEL_LOCATION_XP: '//*[@id="primary"]//*[@id="details-container"]/table/tbody/tr[2]/td[2]/yt-formatted-string',
  CHANNEL_PROFILE_IMAGE_XP: '//*[@id="avatar"]/img',
  CHANNEL_VERIFIED_XP: '//[@id="upload-info"]/ytd-channel-name/ytd-badge-supported-renderer/div[1]/@aria-label',
  CHANNEL_WEBSITE_XP: '//*[@id="primary-links"]/a/div/yt-formatted-string',
  CHANNEL_LINK1_XP: '//*[@id="link-list-container"]/a[1]/div/yt-formatted-string',
  CHANNEL_LINK2_XP: '//*[@id="link-list-container"]/a[2]/div/yt-formatted-string',
  CHANNEL_LINK3_XP: '//*[@id="link-list-container"]/a[3]/div/yt-formatted-string',
  CHANNEL_LINK4_XP: '//*[@id="link-list-container"]/a[4]/div/yt-formatted-string',
  CHANNEL_LINKS_XP: '//*[@id="link-list-container"]',
  LEFT_COLUMN_XP: '//*[@id="left-column"]',
};
