exports.SELECTORS_XP = {
  CHANNEL_NAME_XP: '//div[contains(@class, "hGmWlF")]/h1',
  CHANNEL_SUBSCRIBER_COUNT_XP: '//div[contains(string(), "followers")]/span',
  JOINED_DATE_XP: '//*[@id="right-column"]/yt-formatted-string[2]/span[2]',
  TOTAL_VIEW_COUNT_XP: '//*[@id="right-column"]/yt-formatted-string[3]',
  CHANNEL_DESCRIPTION_XP: '//div/p[contains(@class, "fiNwnS")]',
  CHANNEL_LOCATION_XP: '//*[@id="primary"]//*[@id="details-container"]/table/tbody/tr[2]/td[2]/yt-formatted-string',
  CHANNEL_PROFILE_IMAGE_XP: '//a/div/figure/img[contains(@class, "tw-image-avatar")]',
  CHANNEL_VERIFIED_XP: '//*[@id="root"]/div/div[2]/div[1]/main/div[2]/div[3]/div/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/div[2]/div[1]/div[1]/div/figure/svg',
  CHANNEL_WEBSITE_XP: '//*[@id="primary-links"]/a/div/yt-formatted-string',
  CHANNEL_LINK1_XP: '//div[contains(@class, "social-media-link")]/div/div/a',
  CHANNEL_LINK2_XP: '//div[contains(@class, "social-media-link")][1]/div/div/a',
  CHANNEL_LINK3_XP: '//div[contains(@class, "social-media-link")][2]/div/div/a',
  CHANNEL_LINK4_XP: '//div[contains(@class, "social-media-link")][3]/div/div/a',
  CHANNEL_LINK5_XP: '//div[contains(@class, "social-media-link")][4]/div/div/a',
  CHANNEL_PANELS_XP: '//div[contains(@class, "channel-panels-container")]',
  LEFT_COLUMN_XP: '//*[@id="root"]/div/div[2]/div[1]/main/div[2]/div[3]/div/div/div[1]/div[1]/div[2]/div/div[2]/div/div[2]/div[2]/div',
};
